const {product } = require('../../models'); 

const productData = [
    {
        product_name: 'Jack Daniels',
        price: 20.00,
        stock: 10,
        category_id: 1,
        brand_id: 1,
    },
    {
        product_name: 'Grey Goose',
        price: 30.00,
        stock: 10,
        category_id: 2,
        brand_id: 2,
    },
    {
        product_name: 'Captain Morgan',
        price: 20.00,
        stock: 10,
        category_id: 3,
        brand_id: 3,
    },
    {
        product_name: 'Jose Cuervo',
        price: 20.00,
        stock: 10,
        category_id: 4,
        brand_id: 4,
    },
    {
        product_name: 'Tanqueray',
        price: 20.00,
        stock: 10,
        category_id: 5,
        brand_id: 5,
    },
    {
        product_name: 'Hennessy',
        price: 20.00,
        stock: 10,
        category_id: 6,
        brand_id: 6,
    },
    {
        product_name: 'Bacardi',
        price: 20.00,
        stock: 10,
        category_id: 3, 
        brand_id: 7,
    },
    {
        product_name: 'Patron',
        price: 20.00,
        stock: 10,
        category_id: 4,
        brand_id: 8,
    },
    {
        product_name: 'Bombay Sapphire',
        price: 20.00,
        stock: 10,
        category_id: 5,
        brand_id: 9,
    },
    {
        product_name: 'Remy Martin',
        price: 20.00,
        stock: 10,
        category_id: 6,
        brand_id: 10,
    },
    {
        product_name: 'Jameson',
        price: 20.00,
        stock: 10,
        category_id: 1,
        brand_id: 11,
    },
    {
        product_name: 'Ciroc',
        price: 20.00,
        stock: 10,
        category_id: 2,
        brand_id: 12,
    },
    {
        product_name: 'Malibu',
        price: 20.00,
        stock: 10,
        category_id: 3,
        brand_id: 13,
    },
    {
        product_name: 'Don Julio',
        price: 20.00,
        stock: 10,
        category_id: 4,
        brand_id: 14,
    },
    {
        product_name: 'Ketel One',
        price: 20.00,
        stock: 10,
        category_id: 5,
        brand_id: 15,
    },
    {
        product_name: 'Baileys',
        price: 20.00,
        stock: 10,
        category_id: 6,
        brand_id: 16,
    },
    {
        product_name: 'Johnnie Walker',
        price: 20.00,
        stock: 10,
        category_id: 1,
        brand_id: 17,
    },
    {
        product_name: 'Smirnoff',
        price: 20.00,
        stock: 10,
        category_id: 2,
        brand_id: 18,
    },
    {
        product_name: 'Bacardi',
        price: 20.00,
        stock: 10,
        category_id: 3,
        brand_id: 19,
    },
    {
        product_name: '1800',
        price: 20.00,
        stock: 10,
        category_id: 4,
        brand_id: 20,
    },
    {
        product_name: 'Beefeater',
        price: 20.00,
        stock: 10,
        category_id: 5,
        brand_id: 21,
    },
    {
        product_name: 'Courvoisier',
        price: 20.00,
        stock: 10,
        category_id: 6,
        brand_id: 22,
    },
    {
        product_name: 'Sky',
        price: 20.00,
        stock: 10,
        category_id: 2,
        brand_id: 23,
    },
    {
        product_name: 'Absolut',
        price: 20.00,
        stock: 10,
        category_id: 3,
        brand_id: 24,
    },
    {
        product_name: 'Crown Royal',
        price: 20.00,
        stock: 10,
        category_id: 4,
        brand_id: 25,
    }, 
    {
        product_name: 'Tito',
        price: 20.00,
        stock: 10,
        category_id: 5,
        brand_id: 26,
    },
    {
        product_name: 'Martell',
        price: 20.00,
        stock: 10,
        category_id: 6,
        brand_id: 27,
    },
    {
        product_name: 'Fireball',
        price: 20.00,
        stock: 10,
        category_id: 1,
        brand_id: 28,
    },
    {
        product_name: 'Herradura',
        price: 20.00,
        stock: 10,
        category_id: 4,
        brand_id: 29,
    },
    {
        product_name: 'Stoli',
        price: 20.00,
        stock: 10,
        category_id: 5,
        brand_id: 30,
    },
    {
        product_name: 'Courvoisier',
        price: 20.00,
        stock: 10,
        category_id: 6,
        brand_id: 31,
    },
    {
        product_name: 'Black Velvet',
        price: 20.00,
        stock: 10,
        category_id: 1,
        brand_id: 32,
    },
    {
        product_name: 'canadian host',
        price: 20.00,
        stock: 10,
        category_id: 1,
        brand_id: 33,
    },
    {
        product_name: 'burton',
        price: 20.00,
        stock: 10,
        category_id: 2,
        brand_id: 34,
    },
    {
        product_name: 'Five wives Heavenly',
        price: 20.00,
        stock: 10,
        category_id: 2,
        brand_id: 35,
    },
    {
        product_name: 'Five wives Sinful',
        price: 20.00,
        stock: 10,
        category_id: 2,
        brand_id: 36,
    },
    {
        product_name: 'Beehive',
        price: 20.00,
        stock: 10,
        category_id: 5,
        brand_id: 37,
    },
    



