-- INSERT INTo brand ( name)
-- VALUES('Jack  Daniels');
-- INSERT INTO liquor (name,price,volume,type,description,brand_id)
-- VALUES ('Jack Daniels',15,16,'Whiskey','Tennessee Whiskey',1),
--         ('Jameson',20,16,'Whiskey','Irish Whiskey',1),
--         ('Crown Royal',25,16,'Whiskey','Canadian Whiskey',1),
--         ('Bulleit',25,16,'Whiskey','Kentucky Straight Bourbon Whiskey',1),
--         ('Maker''s Mark',25,16,'Whiskey','Kentucky Straight Bourbon Whiskey',1),
--         ('Jim Beam',15,16,'Whiskey','Kentucky Straight Bourbon Whiskey',1),
--         ('Wild Turkey',15,16,'Whiskey','Kentucky Straight Bourbon Whiskey',1),
--         ('Evan Williams',15,16,'Whiskey','Kentucky Straight Bourbon Whiskey',1),
--         ('Seagrams 7',15,16,'Whiskey','Blended Whiskey',1);
        -- ('Jameson', true),
        -- ('Crown Royal',),
        -- ('Bulleit', true),
        -- ('Maker''s Mark', ),
        -- ('Jim Beam', ),
        -- ('Wild Turkey',),
        -- ('Evan Williams',),
        -- ('Seagrams 7', );
       